version: '3'

services:

    app:
        container_name: app
        build: 
            context: .
        environment:
            - TZ=America/Sao_Paulo
        ports:
            - "8080:80"
        networks:
            - net

    sql-server:
        container_name: sql-server
        build:
            context: .
            dockerfile: SqlServerDockerfile
        environment:
            - SA_PASSWORD=vAVv!Z$fn&Vp
            - ACCEPT_EULA=Y
            - TZ=America/Sao_Paulo
        ports:
            - "1433:1433"
        networks:
            - net

networks:
        net: